
.hack_(video_game_series):
title:.hack,
developer:CyberConnect2,
publisher:Bandai,Bandai_Namco_Entertainment,
designer:Hiroshi_Matsuyama,
writer:Kazunori_Itō,
artist:Yoshiyuki_Sadamoto,
composer:Chikayo_Fukuda,
released:Infection,--06-20,--09-09,--12-12,--04-10,2005-11-23,
series:.hack,
genre:Hack_And_Slash_Rpg,
platforms:PlayStation_2,
name:.hack//Game Music Perfect Collection,
artist:Chikayo_Fukuda,
released:--04-23,
genre:Video_game_music,
length:Disc 1: 68:50,Disc 2: 71:27,